version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/source/api/movies backend/movies -f -e -d 2
      - sphinx-apidoc -o docs/source/api/users  backend/users  -f -e -d 2

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: ../requirements.txt