# Generated by Django 4.2.27 on 2025-12-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tittle", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("release_date", models.DateField()),
                ("genre", models.CharField(max_length=50)),
                ("rating", models.FloatField()),
                ("cast", models.JSONField(blank=True, null=True)),
            ],
            options={"ordering": ["-tittle"]},
        )
    ]
