# Generated by Django 4.2.27 on 2025-12-15 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movies", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 0.0), ("rating__lte", 5.0)),
                name="movies_rating_between_0_and_5",
            ),
        ),
    ]
