# Generated by Django 4.2.27 on 2025-12-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_tittle_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-title']},
        ),
    ]
